-- =====================================================================
-- SQL 50 — Banners pagos de empresas no carrossel do Início
-- Idempotente (pode rodar mais de uma vez). Sem barras invertidas.
--
--  * banners_pagos      : banner do usuário (imagem no bucket 'banners/<auth_id>/...')
--      status: aguardando_pagamento | comprovante_enviado | ativo | bloqueado | recusado
--      "vencido" = status 'ativo' com ativo_ate <= now() (some do carrossel pela consulta)
--      Renovação de banner ativo: renovacao_pedida_em (status continua 'ativo' até vencer)
--  * banner_pagamentos  : log de pagamentos confirmados pelo admin (valor, quem, quando)
--  * app_flags 'banner_preco_mensal' (value_text '99.90') — editável pelo admin
--
--  Usuário: cria/vê/apaga só os SEUS; não mexe em status/ativo_ate (gatilho + sem UPDATE).
--  Admin: tudo, via RPCs SECURITY DEFINER com checagem is_admin().
--  Público (anon/authenticated): lê só ativos e não vencidos.
-- =====================================================================

-- 1) Tabelas ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.banners_pagos (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id             uuid NOT NULL DEFAULT auth.uid(),
  imagem_url          text NOT NULL,
  titulo              text,
  link                text,
  whatsapp            text,
  status              text NOT NULL DEFAULT 'aguardando_pagamento',
  ativo_ate           timestamptz,
  liberado_em         timestamptz,
  comprovante_em      timestamptz,
  renovacao_pedida_em timestamptz,
  motivo              text,
  criado_em           timestamptz NOT NULL DEFAULT now(),
  atualizado_em       timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.banners_pagos ADD COLUMN IF NOT EXISTS comprovante_em timestamptz;
ALTER TABLE public.banners_pagos ADD COLUMN IF NOT EXISTS renovacao_pedida_em timestamptz;
ALTER TABLE public.banners_pagos ADD COLUMN IF NOT EXISTS motivo text;

ALTER TABLE public.banners_pagos DROP CONSTRAINT IF EXISTS banners_pagos_status_chk;
ALTER TABLE public.banners_pagos ADD CONSTRAINT banners_pagos_status_chk
  CHECK (status IN ('aguardando_pagamento', 'comprovante_enviado', 'ativo', 'bloqueado', 'recusado'));
ALTER TABLE public.banners_pagos DROP CONSTRAINT IF EXISTS banners_pagos_titulo_len;
ALTER TABLE public.banners_pagos ADD CONSTRAINT banners_pagos_titulo_len
  CHECK (titulo IS NULL OR char_length(titulo) <= 60);
ALTER TABLE public.banners_pagos DROP CONSTRAINT IF EXISTS banners_pagos_link_len;
ALTER TABLE public.banners_pagos ADD CONSTRAINT banners_pagos_link_len
  CHECK (link IS NULL OR char_length(link) <= 300);

CREATE INDEX IF NOT EXISTS banners_pagos_auth_idx ON public.banners_pagos (auth_id);
CREATE INDEX IF NOT EXISTS banners_pagos_ativos_idx ON public.banners_pagos (status, ativo_ate);

CREATE TABLE IF NOT EXISTS public.banner_pagamentos (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  banner_id      bigint REFERENCES public.banners_pagos(id) ON DELETE SET NULL,
  auth_id        uuid,                 -- dono do banner (fica mesmo se o banner for apagado)
  valor          numeric(10,2) NOT NULL,
  dias           int NOT NULL DEFAULT 30,
  ativo_ate_novo timestamptz,
  confirmado_por uuid,
  confirmado_em  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS banner_pagamentos_banner_idx ON public.banner_pagamentos (banner_id);
CREATE INDEX IF NOT EXISTS banner_pagamentos_mes_idx ON public.banner_pagamentos (confirmado_em);

-- 2) Preço editável (app_flags do SQL 35) ------------------------------
INSERT INTO public.app_flags (key, value_text)
VALUES ('banner_preco_mensal', '99.90')
ON CONFLICT (key) DO NOTHING;

CREATE OR REPLACE FUNCTION public.banner_preco()
RETURNS numeric
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (SELECT CASE WHEN replace(value_text, ',', '.') ~ '^[0-9]+([.][0-9]{1,2})?$'
                 THEN replace(value_text, ',', '.')::numeric END
       FROM public.app_flags WHERE key = 'banner_preco_mensal'),
    99.90);
$$;

-- 3) Gatilho: usuário não escolhe status/datas; valida imagem/link/whatsapp
CREATE OR REPLACE FUNCTION public.banners_pagos_guard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_admin boolean := COALESCE(public.is_admin(), false);
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NOT v_admin THEN
      IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'banner: login necessário' USING ERRCODE = '42501';
      END IF;
      NEW.auth_id := auth.uid();
      NEW.status := 'aguardando_pagamento';
      NEW.ativo_ate := NULL;
      NEW.liberado_em := NULL;
      NEW.comprovante_em := NULL;
      NEW.renovacao_pedida_em := NULL;
      NEW.motivo := NULL;
      -- só imagem do próprio usuário no bucket 'banners'
      IF position('/storage/v1/object/public/banners/' || auth.uid()::text || '/' IN COALESCE(NEW.imagem_url, '')) = 0 THEN
        RAISE EXCEPTION 'banner: imagem inválida' USING ERRCODE = '22023';
      END IF;
    END IF;
    NEW.criado_em := now();
  END IF;
  NEW.titulo := NULLIF(btrim(COALESCE(NEW.titulo, '')), '');
  NEW.link := NULLIF(btrim(COALESCE(NEW.link, '')), '');
  IF NEW.link IS NOT NULL AND NEW.link !~* '^https?://[^ ]+$' THEN
    NEW.link := NULL;
  END IF;
  NEW.whatsapp := NULLIF(regexp_replace(COALESCE(NEW.whatsapp, ''), '[^0-9]', '', 'g'), '');
  IF NEW.whatsapp IS NOT NULL AND char_length(NEW.whatsapp) NOT BETWEEN 10 AND 13 THEN
    NEW.whatsapp := NULL;
  END IF;
  NEW.atualizado_em := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_banners_pagos_guard ON public.banners_pagos;
CREATE TRIGGER trg_banners_pagos_guard
  BEFORE INSERT OR UPDATE ON public.banners_pagos
  FOR EACH ROW EXECUTE FUNCTION public.banners_pagos_guard();

-- 4) RLS ----------------------------------------------------------------
ALTER TABLE public.banners_pagos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banner_pagamentos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "banners_pagos_select_publico" ON public.banners_pagos;
DROP POLICY IF EXISTS "banners_pagos_select_own" ON public.banners_pagos;
DROP POLICY IF EXISTS "banners_pagos_insert_own" ON public.banners_pagos;
DROP POLICY IF EXISTS "banners_pagos_delete_own" ON public.banners_pagos;
DROP POLICY IF EXISTS "banners_pagos_admin_all" ON public.banners_pagos;

CREATE POLICY "banners_pagos_select_publico" ON public.banners_pagos
  FOR SELECT TO anon, authenticated
  USING (status = 'ativo' AND ativo_ate > now());
CREATE POLICY "banners_pagos_select_own" ON public.banners_pagos
  FOR SELECT TO authenticated
  USING (auth_id = auth.uid());
CREATE POLICY "banners_pagos_insert_own" ON public.banners_pagos
  FOR INSERT TO authenticated
  WITH CHECK (auth_id = auth.uid() AND status = 'aguardando_pagamento' AND ativo_ate IS NULL);
CREATE POLICY "banners_pagos_delete_own" ON public.banners_pagos
  FOR DELETE TO authenticated
  USING (auth_id = auth.uid());
CREATE POLICY "banners_pagos_admin_all" ON public.banners_pagos
  FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "banner_pagamentos_select_own" ON public.banner_pagamentos;
DROP POLICY IF EXISTS "banner_pagamentos_admin_all" ON public.banner_pagamentos;
CREATE POLICY "banner_pagamentos_select_own" ON public.banner_pagamentos
  FOR SELECT TO authenticated
  USING (auth_id = auth.uid());
CREATE POLICY "banner_pagamentos_admin_all" ON public.banner_pagamentos
  FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

REVOKE ALL ON TABLE public.banners_pagos FROM anon, authenticated;
REVOKE ALL ON TABLE public.banner_pagamentos FROM anon, authenticated;
GRANT SELECT ON TABLE public.banners_pagos TO anon;
GRANT SELECT, INSERT, DELETE ON TABLE public.banners_pagos TO authenticated;
GRANT UPDATE ON TABLE public.banners_pagos TO authenticated;          -- só passa na policy de admin
GRANT SELECT ON TABLE public.banner_pagamentos TO authenticated;
GRANT INSERT, UPDATE, DELETE ON TABLE public.banner_pagamentos TO authenticated; -- só admin (policy)

-- 5) RPCs ----------------------------------------------------------------
-- Carrossel: ativos e não vencidos (sem expor dono)
DROP FUNCTION IF EXISTS public.banners_pagos_ativos();
CREATE FUNCTION public.banners_pagos_ativos()
RETURNS TABLE (id bigint, imagem_url text, titulo text, link text, whatsapp text, ativo_ate timestamptz)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT b.id, b.imagem_url, b.titulo, b.link, b.whatsapp, b.ativo_ate
    FROM public.banners_pagos b
   WHERE b.status = 'ativo' AND b.ativo_ate > now()
   ORDER BY b.liberado_em DESC NULLS LAST, b.id DESC
   LIMIT 30;
$$;

-- Dono: "Já enviei o comprovante"
CREATE OR REPLACE FUNCTION public.banner_marcar_comprovante(p_id bigint)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  b public.banners_pagos;
BEGIN
  SELECT * INTO b FROM public.banners_pagos WHERE id = p_id AND auth_id = auth.uid();
  IF NOT FOUND THEN
    RAISE EXCEPTION 'banner: não encontrado' USING ERRCODE = 'P0002';
  END IF;
  IF b.status IN ('bloqueado', 'recusado') THEN
    RAISE EXCEPTION 'banner: %', b.status USING ERRCODE = '42501';
  END IF;
  UPDATE public.banners_pagos
     SET comprovante_em = now(),
         status = CASE WHEN status = 'aguardando_pagamento' THEN 'comprovante_enviado' ELSE status END
   WHERE id = p_id
   RETURNING status INTO b.status;
  RETURN b.status;
END;
$$;

-- Dono: "Renovar" (paga de novo; admin libera +30 dias a partir de max(now, ativo_ate))
CREATE OR REPLACE FUNCTION public.banner_pedir_renovacao(p_id bigint)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  b public.banners_pagos;
BEGIN
  SELECT * INTO b FROM public.banners_pagos WHERE id = p_id AND auth_id = auth.uid();
  IF NOT FOUND THEN
    RAISE EXCEPTION 'banner: não encontrado' USING ERRCODE = 'P0002';
  END IF;
  IF b.status IN ('bloqueado', 'recusado') THEN
    RAISE EXCEPTION 'banner: %', b.status USING ERRCODE = '42501';
  END IF;
  UPDATE public.banners_pagos
     SET renovacao_pedida_em = CASE WHEN status = 'ativo' AND ativo_ate > now() THEN now() ELSE NULL END,
         comprovante_em = NULL,
         status = CASE WHEN status = 'ativo' AND ativo_ate > now() THEN 'ativo' ELSE 'aguardando_pagamento' END
   WHERE id = p_id
   RETURNING status INTO b.status;
  RETURN b.status;
END;
$$;

-- Admin: Liberar (registra pagamento do preço atual, +dias a partir de max(now, ativo_ate))
CREATE OR REPLACE FUNCTION public.banner_admin_liberar(p_id bigint, p_valor numeric DEFAULT NULL, p_dias int DEFAULT 30)
RETURNS timestamptz
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  b public.banners_pagos;
  v_ate timestamptz;
  v_valor numeric := COALESCE(p_valor, public.banner_preco());
  v_dias int := GREATEST(1, LEAST(COALESCE(p_dias, 30), 366));
BEGIN
  IF NOT COALESCE(public.is_admin(), false) THEN
    RAISE EXCEPTION 'banner: só admin' USING ERRCODE = '42501';
  END IF;
  SELECT * INTO b FROM public.banners_pagos WHERE id = p_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'banner: não encontrado' USING ERRCODE = 'P0002';
  END IF;
  v_ate := GREATEST(now(), COALESCE(b.ativo_ate, now())) + make_interval(days => v_dias);
  UPDATE public.banners_pagos
     SET status = 'ativo', ativo_ate = v_ate, liberado_em = now(),
         renovacao_pedida_em = NULL, comprovante_em = NULL, motivo = NULL
   WHERE id = p_id;
  INSERT INTO public.banner_pagamentos (banner_id, auth_id, valor, dias, ativo_ate_novo, confirmado_por)
  VALUES (p_id, b.auth_id, v_valor, v_dias, v_ate, auth.uid());
  RETURN v_ate;
END;
$$;

-- Admin: Bloquear / Recusar (ou voltar para aguardando)
CREATE OR REPLACE FUNCTION public.banner_admin_status(p_id bigint, p_status text, p_motivo text DEFAULT NULL)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT COALESCE(public.is_admin(), false) THEN
    RAISE EXCEPTION 'banner: só admin' USING ERRCODE = '42501';
  END IF;
  IF p_status NOT IN ('bloqueado', 'recusado', 'aguardando_pagamento') THEN
    RAISE EXCEPTION 'banner: status inválido' USING ERRCODE = '22023';
  END IF;
  UPDATE public.banners_pagos
     SET status = p_status, motivo = NULLIF(btrim(COALESCE(p_motivo, '')), ''), renovacao_pedida_em = NULL
   WHERE id = p_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'banner: não encontrado' USING ERRCODE = 'P0002';
  END IF;
  RETURN p_status;
END;
$$;

-- Admin: lista com dono, contato e pagamentos
DROP FUNCTION IF EXISTS public.banner_admin_lista();
CREATE FUNCTION public.banner_admin_lista()
RETURNS TABLE (
  id bigint, auth_id uuid, imagem_url text, titulo text, link text, whatsapp text,
  status text, ativo_ate timestamptz, liberado_em timestamptz, comprovante_em timestamptz,
  renovacao_pedida_em timestamptz, motivo text, criado_em timestamptz,
  dono_nome text, dono_apelido text, dono_email text, dono_telefone text,
  n_pagamentos bigint, total_pago numeric, ultimo_valor numeric, ultimo_pagamento_em timestamptz
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT COALESCE(public.is_admin(), false) THEN
    RAISE EXCEPTION 'banner: só admin' USING ERRCODE = '42501';
  END IF;
  RETURN QUERY
  SELECT b.id, b.auth_id, b.imagem_url, b.titulo, b.link, b.whatsapp,
         b.status, b.ativo_ate, b.liberado_em, b.comprovante_em,
         b.renovacao_pedida_em, b.motivo, b.criado_em,
         u.nome::text, (to_jsonb(u) ->> 'apelido'), (to_jsonb(u) ->> 'email'),
         COALESCE(to_jsonb(u) ->> 'telefone', to_jsonb(u) ->> 'whatsapp'),
         COALESCE(p.n, 0), COALESCE(p.total, 0), p.ult_valor, p.ult_em
    FROM public.banners_pagos b
    LEFT JOIN LATERAL (SELECT * FROM public.usuarios x WHERE x.auth_id = b.auth_id LIMIT 1) u ON true
    LEFT JOIN LATERAL (
      SELECT count(*) AS n, sum(g.valor) AS total,
             (array_agg(g.valor ORDER BY g.confirmado_em DESC))[1] AS ult_valor,
             max(g.confirmado_em) AS ult_em
        FROM public.banner_pagamentos g WHERE g.banner_id = b.id
    ) p ON true
   ORDER BY b.criado_em DESC
   LIMIT 500;
END;
$$;

-- Admin: total recebido por mês (fuso de Belém)
DROP FUNCTION IF EXISTS public.banner_admin_totais_mes();
CREATE FUNCTION public.banner_admin_totais_mes()
RETURNS TABLE (mes text, n bigint, total numeric)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT COALESCE(public.is_admin(), false) THEN
    RAISE EXCEPTION 'banner: só admin' USING ERRCODE = '42501';
  END IF;
  RETURN QUERY
  SELECT to_char(g.confirmado_em AT TIME ZONE 'America/Belem', 'YYYY-MM') AS mes, count(*), sum(g.valor)
    FROM public.banner_pagamentos g
   GROUP BY 1 ORDER BY 1 DESC LIMIT 24;
END;
$$;

REVOKE ALL ON FUNCTION public.banner_preco() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.banners_pagos_ativos() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.banner_marcar_comprovante(bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.banner_pedir_renovacao(bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.banner_admin_liberar(bigint, numeric, int) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.banner_admin_status(bigint, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.banner_admin_lista() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.banner_admin_totais_mes() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.banners_pagos_guard() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.banner_preco() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.banners_pagos_ativos() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.banner_marcar_comprovante(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.banner_pedir_renovacao(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.banner_admin_liberar(bigint, numeric, int) TO authenticated;
GRANT EXECUTE ON FUNCTION public.banner_admin_status(bigint, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.banner_admin_lista() TO authenticated;
GRANT EXECUTE ON FUNCTION public.banner_admin_totais_mes() TO authenticated;

-- 6) Storage: bucket público 'banners', pasta por usuário ---------------
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('banners', 'banners', true, 2097152, ARRAY['image/webp', 'image/jpeg', 'image/png'])
ON CONFLICT (id) DO UPDATE
   SET public = true,
       file_size_limit = 2097152,
       allowed_mime_types = ARRAY['image/webp', 'image/jpeg', 'image/png'];

DROP POLICY IF EXISTS "banners_select_public" ON storage.objects;
DROP POLICY IF EXISTS "banners_insert_own" ON storage.objects;
DROP POLICY IF EXISTS "banners_update_own" ON storage.objects;
DROP POLICY IF EXISTS "banners_delete_own" ON storage.objects;

CREATE POLICY "banners_select_public" ON storage.objects
  FOR SELECT TO anon, authenticated
  USING (bucket_id = 'banners');
CREATE POLICY "banners_insert_own" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'banners' AND auth.uid() IS NOT NULL
              AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY "banners_update_own" ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'banners' AND (storage.foldername(name))[1] = auth.uid()::text)
  WITH CHECK (bucket_id = 'banners' AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY "banners_delete_own" ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'banners'
         AND ((storage.foldername(name))[1] = auth.uid()::text OR public.is_admin()));

NOTIFY pgrst, 'reload schema';

-- 7) Conferência: esperado tabelas=2 | rpcs=8 | gatilho=1 | bucket=1 | policies_storage=4 | policies_tabelas=7 | preco=99.90 (ou o valor salvo)
SELECT
  (SELECT count(*) FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name IN ('banners_pagos', 'banner_pagamentos')) AS tabelas,
  (SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.proname IN ('banner_preco', 'banners_pagos_ativos', 'banner_marcar_comprovante',
      'banner_pedir_renovacao', 'banner_admin_liberar', 'banner_admin_status', 'banner_admin_lista', 'banner_admin_totais_mes')) AS rpcs,
  (SELECT count(*) FROM pg_trigger WHERE tgname = 'trg_banners_pagos_guard') AS gatilho,
  (SELECT count(*) FROM storage.buckets WHERE id = 'banners') AS bucket,
  (SELECT count(*) FROM pg_policies WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname IN ('banners_select_public', 'banners_insert_own', 'banners_update_own', 'banners_delete_own')) AS policies_storage,
  (SELECT count(*) FROM pg_policies WHERE schemaname = 'public' AND tablename IN ('banners_pagos', 'banner_pagamentos')) AS policies_tabelas,
  public.banner_preco() AS preco;
